#!/bin/perl
use Net::OpenStack::Ceilometer;
use Data::Dumper;
use Getopt::Long;

use strict;
use warnings;

my $a = Net::OpenStack::Ceilometer->new(
    host     => '192.168.0.177',
    username => 'admin',
    password => '6507ed71383b4544', # TODO: Load this from config
);

our $HELP = 0;
our $METER = '';

# {{{ GetOpt
unless (
    GetOptions(
        'help'    => \$HELP,
        'meter=s' => \$METER,
    )
  )
{
    usage( '', 1 );
} # }}}

if ($METER) {
    print Dumper( $a->meter_by_name($METER) );
} else {
    my $meters = $a->meters();
    foreach my $m (@$meters) {
        print $m->{name} . "\t";
        print $m->{unit} . "\t";
        print $m->{meter_id} . "\n";
    }
}

sub usage { # {{{
    my $message = shift || '';
    my $exit_code = shift || 0;
    print(<<EOU);
$message

$0 {--usage | --help}
  Display this message.

$0 -m 'meter_name'
    Shows info about the specified meter. (Note that names may not be
    unique.)

Lists all meters collected

EOU
    exit($exit_code);
} # }}}


