#!/bin/perl
use Net::OpenStack::Ceilometer;
use Data::Dumper;

my $a = Net::OpenStack::Ceilometer->new(
    host     => '192.168.0.177',
    username => 'admin',
    password => '6507ed71383b4544', # This should be in a config file, eh?
);

my $resources = $a->resources();
foreach my $r ( @$resources ) {
    print $r->{name} . "\n";
    print Dumper( $r );
}
