#!/bin/perl
use Net::OpenStack::Ceilometer;
use Data::Dumper;
use Getopt::Long;

use strict;
use warnings;

my $a = Net::OpenStack::Ceilometer->new(
    host     => '192.168.0.177',
    username => 'admin',
    password => '6507ed71383b4544', # TODO: Load this from config
);

our $HELP  = 0;
our $METER = '';

# {{{ GetOpt
unless (
    GetOptions(
        'help'    => \$HELP,
        'meter=s' => \$METER,
    )
  )
{
    usage( '', 1 );
} # }}}

if ($METER) {

    # Get the meter object first
    my $meter = $a->meter_by_id( $METER );

    my $stats = $a->statistics(
        $meter->{name},
        [ # order matters!
            [
                'field' => 'resource_id',
                'op'    => 'eq',
                'value' => $meter->{resource_id},
            ],
            # [
                # "field" => "timestamp",
                # "op"    => "ge",
                # "value" => "2012-01-22T15:40:00"
            # ],
            # [
                # "field" => "timestamp",
                # "op"    => "lt",
                # "value" => "2014-01-22T16:00:00"
            # ],
        ]
    );

    print Dumper( $stats );
} else {
    usage("You must specify a meter you wish to have stats on.", 0);
}


sub usage { # {{{
    my $message = shift || '';
    my $exit_code = shift || 0;
    print(<<EOU);
$message

$0 {--usage | --help}
  Display this message.

$0 -m 'meter_name'
    Dumps stats for that meter

Display statistics for a specified meter.

EOU
    exit($exit_code);
} # }}}
