#!/bin/perl
use Net::OpenStack::Ceilometer;
use Data::Dumper;
use Getopt::Long;

use strict;
use warnings;

my $a = Net::OpenStack::Ceilometer->new(
    host     => '192.168.0.177',
    username => 'admin',
    password => '885d4b669cc04a1b', # TODO: Load this from config
);

our $HELP  = 0;
our $METER = '';

# {{{ GetOpt
unless (
    GetOptions(
        'help'    => \$HELP,
        'meter=s' => \$METER,
    )
  )
{
    usage( '', 1 );
} # }}}

if ($METER) {

    # Get the meter object first
    my $meter = $a->meter_by_id( $METER );
    warn Dumper( $meter );

    my $stats = $a->statistics(
        $METER,
        [
            {
                'field' => 'resource_id',
                'op'    => 'eq',
                'value' => $meter->{resource_id},
            }
        ]
    );

    print Dumper( $stats );
} else {
    usage("You must specify a meter you wish to have stats on.", 0);
}


sub usage { # {{{
    my $message = shift || '';
    my $exit_code = shift || 0;
    print(<<EOU);
$message

$0 {--usage | --help}
  Display this message.

$0 -m 'meter_name'
    Dumps stats for that meter

Display statistics for a specified meter.

EOU
    exit($exit_code);
} # }}}
